version: '3.8'
services:
  db:
    image: postgres:13
    restart: always
    env_file:
      - backend/.env
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    # depends_on:
    #   - db

  backend:
    build:
      context: ./backend
      # command: bash -c "poetry run bash ./prestart.sh && poetry run uvicorn app.main:app --reload --host 0.0.0 --port 8000"
    # ports:
    #   - "8000:8000"
    env_file:
      - backend/.env
    # environment:
    #   PYTHONPATH: /app
    depends_on:
      - db

  nginx:
    build:
      context: ./frontend
    ports:
      - "80:80"
    env_file:
      - frontend/.env
    depends_on:
      - backend
