version: '3.8'
services:
  db:
    image: postgres:13
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: changethis123
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - db

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    environment:
      PYTHONPATH: /app
    depends_on:
      - db

  nginx:
    build:
      context: ./frontend
    ports:
      - "80:80"
    env_file:
      - frontend/.env
    depends_on:
      - backend
